CREATE TABLE HARDWARE (
    ID IDENTITY PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    CODE VARCHAR(50) NOT NULL UNIQUE,
    PRICE DECIMAL(10, 2) NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
    AMOUNT INT NOT NULL
);

